loading checkpoint '/results/simple_MLP/timesformer/best_epoch.pt'
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.09it/s]
Traceback (most recent call last):
  File "../main.py", line 160, in <module>
    main()
  File "../main.py", line 148, in main
    avg_loss,top1,top5 = test_model(config,test_ds)
  File "/workspace/tfg_hhernandez/utils/evaluate.py", line 67, in test_model
    return evaluation(model, test_loader, criterion)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/tfg_hhernandez/utils/evaluate.py", line 43, in evaluation
    top1_acc = top_k_accuracy_score(y_true, y_score, k=1)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_ranking.py", line 1916, in top_k_accuracy_score
    y_true = column_or_1d(y_true)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 1244, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (85, 32) instead.
